name: Auto Sitemap
description: A GitHub Action that generates a sitemap XML file based on the files in the repository.
author: cemreefe

on:
  push:
    branches:
      - main
      - master
      - gh-pages

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'python3 sitemap.py'

  steps:
    - name: Commit changes
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add -A 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
