name: Auto Sitemap
description: A GitHub Action that generates a sitemap XML file based on the files in the repository.
author: cemreefe

on:
  push:
    branches:
      - main
      - master
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate sitemap
        run: python3 sitemap.py
      - name: Commit changes
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Update sitemap"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
