name: Auto Sitemap
description: A GitHub Action that generates a sitemap XML file based on the files in the repository.
author: cemreefe

on:
  push:
    branches:
      - main

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.workspace }}
  entrypoint: 'python3 sitemap.py'
